export const AFFILIATE_TAG = "jackkg-20";

export function getAmazonLink(query: string) {
  return `https://www.amazon.com/s?k=${encodeURIComponent(query)}&tag=${AFFILIATE_TAG}`;
}

export interface Product {
  id: number;
  name: string;
  cat: string;
  price: number;
  old: number | null;
  rat: number;
  rev: number;
  badge: string | null;
  tags: string[];
  desc: string;
  img: string;
  q: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Flowy Linen Dress",
    cat: "Fashion",
    price: 68,
    old: 95,
    rat: 4.8,
    rev: 234,
    badge: "New",
    tags: ["New"],
    desc: "Breathable and elegant for warm days.",
    img: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&q=80",
    q: "linen dress women",
  },
  {
    id: 2,
    name: "Strut It Shorts",
    cat: "Fashion",
    price: 42,
    old: null,
    rat: 4.6,
    rev: 88,
    badge: null,
    tags: [],
    desc: "The perfect everyday casual shorts.",
    img: "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=500&q=80",
    q: "women casual shorts",
  },
  {
    id: 3,
    name: "Sparkle Pendant Necklace",
    cat: "Fashion",
    price: 29,
    old: 45,
    rat: 4.9,
    rev: 412,
    badge: "Sale",
    tags: ["Sale"],
    desc: "Delicate gold-tone pendant for any outfit.",
    img: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&q=80",
    q: "gold pendant necklace women",
  },
  {
    id: 4,
    name: "Feel Good Body Scrub",
    cat: "Health & Wellness",
    price: 22,
    old: null,
    rat: 4.7,
    rev: 156,
    badge: null,
    tags: ["Organic"],
    desc: "Natural exfoliating scrub with sweet almond oil.",
    img: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500&q=80",
    q: "natural body scrub almond oil",
  },
  {
    id: 5,
    name: "Artisan Bar Soap Set",
    cat: "Health & Wellness",
    price: 14,
    old: null,
    rat: 4.5,
    rev: 320,
    badge: null,
    tags: ["Eco-friendly", "Vegan"],
    desc: "Cold-process artisan soap, zero waste packaging.",
    img: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&q=80",
    q: "natural artisan bar soap set",
  },
  {
    id: 6,
    name: "SPF 35 Daily Sunscreen",
    cat: "Health & Wellness",
    price: 18,
    old: 24,
    rat: 4.9,
    rev: 780,
    badge: "Sale",
    tags: ["Sale"],
    desc: "Daily moisturizer with broad spectrum protection.",
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&q=80",
    q: "daily moisturizer SPF 35 sunscreen",
  },
  {
    id: 7,
    name: "Organic Bamboo Sheets",
    cat: "Home & Lifestyle",
    price: 89,
    old: 120,
    rat: 4.8,
    rev: 567,
    badge: "Sale",
    tags: ["Sale", "Organic", "Eco-friendly"],
    desc: "Ultra-soft 400TC bamboo, cool and breathable.",
    img: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500&q=80",
    q: "organic bamboo bed sheets queen",
  },
  {
    id: 8,
    name: "Ceramic Pour-Over Set",
    cat: "Home & Lifestyle",
    price: 54,
    old: null,
    rat: 4.7,
    rev: 203,
    badge: "New",
    tags: ["New", "Handmade"],
    desc: "Hand-thrown ceramic pour-over coffee set.",
    img: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&q=80",
    q: "ceramic pour over coffee set handmade",
  },
  {
    id: 9,
    name: "Matcha Starter Kit",
    cat: "Food & Drink",
    price: 35,
    old: null,
    rat: 4.6,
    rev: 144,
    badge: null,
    tags: ["Organic", "Vegan"],
    desc: "Ceremonial grade matcha + bamboo whisk.",
    img: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&q=80",
    q: "ceremonial matcha starter kit bamboo whisk",
  },
  {
    id: 10,
    name: "Wireless Earbuds Pro",
    cat: "Tech",
    price: 79,
    old: 129,
    rat: 4.8,
    rev: 1204,
    badge: "Sale",
    tags: ["Sale"],
    desc: "24hr battery life, active noise cancellation.",
    img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&q=80",
    q: "wireless earbuds noise cancelling pro",
  },
  {
    id: 11,
    name: "Reusable Produce Bags",
    cat: "Zero Waste",
    price: 16,
    old: null,
    rat: 4.9,
    rev: 890,
    badge: null,
    tags: ["Eco-friendly", "Vegan"],
    desc: "Set of 9 mesh bags, machine washable.",
    img: "https://images.unsplash.com/photo-1542601906897-c048b1e18538?w=500&q=80",
    q: "reusable mesh produce bags set eco",
  },
  {
    id: 12,
    name: "Wooden Building Blocks",
    cat: "Kids",
    price: 38,
    old: null,
    rat: 4.8,
    rev: 342,
    badge: "New",
    tags: ["New", "Gift"],
    desc: "Natural beech wood, 50-piece stacking set.",
    img: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500&q=80",
    q: "wooden building blocks kids natural beech",
  },
  {
    id: 13,
    name: "Vitamin C Brightening Serum",
    cat: "Beauty",
    price: 26,
    old: 38,
    rat: 4.7,
    rev: 678,
    badge: "Sale",
    tags: ["Sale", "Vegan"],
    desc: "20% L-ascorbic acid brightening serum.",
    img: "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=500&q=80",
    q: "vitamin C brightening serum face skincare",
  },
  {
    id: 14,
    name: "Resistance Band Set",
    cat: "Sports",
    price: 32,
    old: null,
    rat: 4.6,
    rev: 512,
    badge: null,
    tags: [],
    desc: "5 resistance levels + carry bag included.",
    img: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500&q=80",
    q: "resistance band set 5 levels workout",
  },
  {
    id: 15,
    name: "Linen Throw Pillow Cover",
    cat: "Home & Lifestyle",
    price: 44,
    old: null,
    rat: 4.5,
    rev: 189,
    badge: null,
    tags: [],
    desc: "Natural linen, removable zipper cover.",
    img: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80",
    q: "natural linen throw pillow cover removable",
  },
  {
    id: 16,
    name: "Smart Watch Fitness",
    cat: "Tech",
    price: 149,
    old: 199,
    rat: 4.7,
    rev: 2301,
    badge: "Sale",
    tags: ["Sale"],
    desc: "Health tracking, 7-day battery, swim-proof.",
    img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80",
    q: "smart watch fitness health tracking waterproof",
  },
  {
    id: 17,
    name: "Cold Brew Coffee Kit",
    cat: "Food & Drink",
    price: 28,
    old: null,
    rat: 4.6,
    rev: 203,
    badge: "New",
    tags: ["New"],
    desc: "Make smooth cold brew at home in 12 hours.",
    img: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&q=80",
    q: "cold brew coffee kit home",
  },
  {
    id: 18,
    name: "Premium Yoga Mat",
    cat: "Sports",
    price: 55,
    old: 75,
    rat: 4.8,
    rev: 445,
    badge: "Sale",
    tags: ["Sale", "Eco-friendly"],
    desc: "Non-slip 6mm eco cork yoga mat.",
    img: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&q=80",
    q: "premium yoga mat non slip eco cork",
  },
  {
    id: 19,
    name: "Soy Candle Set",
    cat: "Home & Lifestyle",
    price: 36,
    old: null,
    rat: 4.9,
    rev: 621,
    badge: null,
    tags: ["Vegan", "Gift"],
    desc: "Set of 3 hand-poured soy wax candles.",
    img: "https://images.unsplash.com/photo-1608181831718-c9fbb21934e7?w=500&q=80",
    q: "soy candle set hand poured gift",
  },
  {
    id: 20,
    name: "Kids Watercolor Paint Set",
    cat: "Kids",
    price: 22,
    old: null,
    rat: 4.7,
    rev: 178,
    badge: null,
    tags: ["Gift"],
    desc: "Non-toxic watercolors, 24 vivid colors.",
    img: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&q=80",
    q: "kids watercolor paint set non toxic 24",
  },
];

export const CATEGORIES = [
  { name: "All", icon: null },
  { name: "Fashion", icon: "dress" },
  { name: "Health & Wellness", icon: "pill" },
  { name: "Home & Lifestyle", icon: "home" },
  { name: "Food & Drink", icon: "tea" },
  { name: "Tech", icon: "laptop" },
  { name: "Kids", icon: "toy" },
  { name: "Zero Waste", icon: "recycle" },
  { name: "Beauty", icon: "sparkles" },
  { name: "Sports", icon: "ball" },
];

export const FEATURES = [
  "Eco-friendly",
  "Handmade",
  "Sale",
  "New",
  "Vegan",
  "Organic",
  "Gift",
];

export const MARQUEE_ITEMS = [
  "Fashion",
  "Tech",
  "Home",
  "Wellness",
  "Food",
  "Beauty",
  "Kids",
  "Sports",
  "Zero Waste",
  "Accessories",
];

export function getStarRating(rating: number): string {
  const fullStars = Math.floor(rating);
  const hasHalf = rating % 1 >= 0.5;
  const emptyStars = 5 - Math.ceil(rating);
  return (
    "\u2605".repeat(fullStars) +
    (hasHalf ? "\u00BD" : "") +
    "\u2606".repeat(emptyStars)
  );
}

export const BESTSELLER_IDS = [3, 6, 10, 16, 18];
